### PR TITLE
Override signature provider

### PR DESCRIPTION
**Pull request by adierebel**
Since signing url are mandatory, to make it easier when you want to use external signature provider, we added a function to override the signing process.

### New config:
```javascript
let config = {
    enabled: true,
    signProvider: signProvider,
    signProviderHost: 'https://tiktok.isaackogan.com/',
    signProviderPath: 'webcast/sign_url',
    extraParams: {},
};
```

### Test:
```javascript
const { WebcastPushConnection, signatureProvider } = require('tiktok-live-connector');
const axios = require('axios').create({
    timeout: 5000
});

// Set custom signature provider before connect
signatureProvider.config.signProvider = async function (url, headers, cookieJar, signEvents) {
    try {
        // Get signature from server
        let params = {
            url: url
        }
        let signResponse = await axios.get("https://your-sign-server/sign_url", { params, responseType: 'json' });

        // Set headers
        headers['User-Agent'] = signResponse.data['User-Agent'];

        // Set cookies
        cookieJar.setCookie('msToken', signResponse.data['msToken']);

        // Emit success event
        signEvents.emit('signSuccess', {
            originalUrl: url,
            signedUrl: signResponse.data.signedUrl,
            headers,
            cookieJar,
        });

        // Return signed url
        return signResponse.data.signedUrl;

    } catch (error) {
        // Emit error event
        signEvents.emit('signError', {
            originalUrl: url,
            headers,
            cookieJar,
            error,
        });

        throw new Error(`Failed to sign request: ${error.message}; URL: ${url}`);
    }
}

// Username of someone who is currently live
let tiktokUsername = "officialgeilegisela";

// Create a new wrapper object and pass the username
let tiktokLiveConnection = new WebcastPushConnection(tiktokUsername);

// Connect to the chat (await can be used as well)
tiktokLiveConnection.connect().then(state => {
    console.info(`Connected to roomId ${state.roomId}`);
}).catch(err => {
    console.error('Failed to connect', err);
});
```

### CODE REVIEW

**Comment by NickKlufas** [comment]
Adierebel, if you have access to a working external signing provider I would gladly be willing to pay for access. Can you reach me at nick.klufas@gmail.com to discuss? I couldn't find your twitter or any other way to reach out before commenting on your commit, lol. Thank you!

**Comment by adierebel** [comment]
> Adierebel, if you have access to a working external signing provider I would gladly be willing to pay for access. Can you reach me at [nick.klufas@gmail.com](mailto:nick.klufas@gmail.com) to discuss? I couldn't find your twitter or any other way to reach out before commenting on your commit, lol. Thank you!

I don't have that. You can deploy your own signing server https://github.com/carcabot/tiktok-signature

**Comment by NickKlufas** [comment]
Adierebel Is that the signing server you're using? You can confirm that works? Thank you so much for responding.

**Comment by isaackogan** [comment]
> Adierebel Is that the signing server you're using? You can confirm that works? Thank you so much for responding.

That software is not a signing server, it generates tokens. It does not have support for msToken, but it is a strong step for self-hosting a signing server :)

**Comment by goontea** [comment]
> I don't have that. You can deploy your own signing server https://github.com/carcabot/tiktok-signature
>msToken from automated browser (puppetter/playwright) is invalid. if you take from regular browser (with user logged in) it may work, but sometimes not.
Thanks for your work on this!

Would you be able to provide more detail on how you hook the msToken to the process (from your comment above)? I don't mind if it has to be manually done, I just don't know how to fit it into the workflow for that library.

**Comment by zerodytrash** [comment]
Sorry for the delay here. It might be necessary to restructure the library in the near future. At the moment I am still thinking about how to proceed. Currently, no more signatures are generated for the client. However, we can apply the customizations as an option if someone want to use his own signature provider (which currently does not work reliably because TikTok blocks the IP of the client).

**Pull request closed without merging**
